apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: pods-are-healthy
spec:
  analyzers:
    - deploymentStatus:
        name: coredns
        namespace: kube-system
        outcomes:
          - fail:
              when: "< 1"
              message: CoreDNS does not have any ready replicas.
          - warn:
              when: "= 1"
              message: CoreDNS has only a single ready replica.
          - pass:
              message: There are multiple replicas of CoreDNS deployment ready.
    - deploymentStatus:
        name: cluster-autoscaler
        namespace: kube-system
        outcomes:
          - fail:
              when: "< 1"
              message: Cluster-autoscaler does not have any ready replicas.
          - pass:
              message: Cluster-autoscaler is running.
    - deploymentStatus:
        name: external-dns
        namespace: kube-system
        outcomes:
          - fail:
              when: "< 1"
              message: External-DNS does not have any ready replicas.
          - pass:
              message: External-DNS is running.
    - deploymentStatus:
        name: cert-manager-controller
        namespace: kube-system
        outcomes:
          - fail:
              when: "< 1"
              message: CertManager does not have any ready replicas.
          - pass:
              message: CertManager is running.
    # Check if all deployments are satisfied
    - deploymentStatus:
        namespace: kube-system
    - clusterPodStatuses:
        name: unhealthy
        namespaces:
          - kube-system
        outcomes:
          - fail:
              when: "!= Healthy"
              message: Pod {{ .Namespace }}/{{ .Name }} is unhealthy with a status of {{ .Status.Reason }}.